export const LANGUAGES = [
  ["en", "English", "🇬🇧"],
  ["es", "Spanish", "🇪🇸"],
  ["fr", "French", "🇫🇷"],
  ["de", "German", "🇩🇪"],
  ["zh", "Chinese", "🇨🇳"],
  ["hi", "Hindi", "🇮🇳"],
  ["ar", "Arabic", "🇦🇪"],
  ["pt", "Portuguese", "🇵🇹"],
  ["ru", "Russian", "🇷🇺"],
  ["ja", "Japanese", "🇯🇵"],
  ["ko", "Korean", "🇰🇷"],
  ["it", "Italian", "🇮🇹"],
  ["tr", "Turkish", "🇹🇷"],
  ["nl", "Dutch", "🇳🇱"],
  ["sv", "Swedish", "🇸🇪"],
  ["pl", "Polish", "🇵🇱"],
  ["fa", "Persian", "🇮🇷"],
  ["fi", "Finnish", "🇫🇮"],
  ["cs", "Czech", "🇨🇿"],
  ["id", "Indonesian", "🇮🇩"],
  ["he", "Hebrew", "🇮🇱"],
];